spring:
  datasource:
    url: jdbc:mysql://47.98.112.176:3307/dev_xt?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/list/
    suffix: .html

server:
  port: 80
